_BASE_: "../../../../configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"

MODEL:
  LOAD_PROPOSALS: False
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"

DATASETS:
  TRAIN: ("grg_train",)
  TEST: ("grg_val",)
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 10000
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 10000

TRAINER:
  NAME: "GRGTrainer"

DATALOADER:
  NUM_WORKERS: 4

SOLVER:
  IMS_PER_BATCH: 16   # Swin is heavier, reduce batch if GPU is limited
  BASE_LR: 0.0005
  STEPS: (46800, 62400, 112000)
  MAX_ITER: 178000
  CHECKPOINT_PERIOD: 2500
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER_NAME: "WarmupCosineLR"

INPUT:
  MIN_SIZE_TRAIN: (300,)  # Match your image size
  MAX_SIZE_TRAIN: 300
  MIN_SIZE_TEST: 300
  MAX_SIZE_TEST: 300
  MASK_FORMAT: "bitmask"  # Use "bitmask" for RLE format annotations

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "/home/s4861264/detectron2/projects/LoTSS-GRG-detect/output/grg_mask_rcnn_101fpn"