_BASE_: "../../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  # WEIGHTS: "/home/s4861264/detectron2/projects/LoTSS-GRG-detect/output/grg_mask_rcnn_b2s/model_0054999.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 2  # MCS and SCS classes
    SCORE_THRESH_TEST: 0.5  # Adjust based on validation performance
  ROI_MASK_HEAD:
    POOLER_RESOLUTION: 28  # Increase mask resolution from default 14
  # We load precomputed proposals in custom mapper (from NPZ files)
  # So LOAD_PROPOSALS should be False (it expects pickle files)
  LOAD_PROPOSALS: False
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
DATASETS:
  TRAIN: ("b2s_train",)
  TEST: ("b2s_val",)
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 10000
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 10000
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.5  # images with category frequency below 50% get repeated
TRAINER:
  NAME: "GRGTrainer"
DATALOADER:
  NUM_WORKERS: 4  # Adjust based on your CPU cores
SOLVER:
  IMS_PER_BATCH: 16  # Adjust based on your GPU memory
  BASE_LR: 0.001
  STEPS: (46800, 62400, 112000)  # Adjust based on your dataset size and desired schedule
  MAX_ITER: 178000
  CHECKPOINT_PERIOD: 2500
  WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (300,)  # Match your image size
  MAX_SIZE_TRAIN: 300
  MIN_SIZE_TEST: 300
  MAX_SIZE_TEST: 300
  MASK_FORMAT: "bitmask"  # Use "bitmask" for RLE format annotations
TEST:
  EVAL_PERIOD: 10000  # Evaluate every 10000 iterations
  EVALUATOR: "B2SMaskedRCNNEvaluator" # or 'B2SEvaluator' if using two_classes=False
OUTPUT_DIR: "/home/s4861264/detectron2/projects/LoTSS-GRG-detect/output/mask_rcnn_b2s_v2"

# V1:
# - Added dataloader sampler to address class imbalance (RepeatFactorTrainingSampler with 0.5 threshold)

# V2:
# - Added class weight to FastRCNNOutputLayers of 2 for MCS class (class ID 2) and 1 for other classes,
#   to address class imbalance. This is implemented in the compute_loss method of FastRCNNOutputLayers,
#   where we create a weight tensor that assigns a weight of 3.0 to the MCS class and 1.0 to all other classes,
#   and use this weight tensor to scale the classification loss. We do not apply any weighting to the background class.