_BASE_: "../../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TailedRCNN"
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PHYSICS_FAN:
    NUM_COMPONENTS: 10  # Adjust based on your component definition
    NUM_PHYSICS_FEATURES: 10  # Size of physics feature vector
    EMBEDDING_DIM: 256  # Size of component embeddings
    EMBEDDING_DROPOUT: 0.1  # Dropout for MLP embeddings
    NUM_ATTENTION_HEADS: 8
    ATTENTION_DROPOUT: 0.1
  FUSION_MODULE:
    TYPE: "AttentionFusionModule" # Either this or "Concatenation"
    DROPOUT: 0.1
    NUM_HEADS: 8
  ROI_ALIGN:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    POOLER_RESOLUTION: 28 # Increase from default 14 to 28 for better spatial detail
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"  # Use ROIAlignV2 for better performance with small objects
  VALIDITY_HEAD:
    LOSS_WEIGHT: 1.0  # Weight for the validity classification loss
    HIDDEN_DIM: 256  # Hidden dimension for the validity head MLP
    SCORE_THRESH_TEST: 0.5  # Threshold for filtering proposals based on validity score during testing
    DECOUPLE_PROJECTION: True  # Use a separate projection branch for validity features

    # Whether to treat membership as a binary classification (member vs non-member) or
    # two classes multi-component source (MCS), single-component source (SCS), and invalid
    TWO_CLASSES: False
  MEMBERSHIP_HEAD:
    LOSS_WEIGHT: 1.0  # Weight for the membership classification loss
    HIDDEN_DIM: 256  # Hidden dimension for the membership head MLP
    NUM_HEADS: 4  # Number of attention heads for the validity head
    DROPOUT: 0.1  # Dropout for the validity head MLP
    SCORE_THRESH_TEST: 0.5  # Threshold for filtering proposals based on membership score during testing
  # Backward compatibility (doesn't do anything) ---
  LOAD_PROPOSALS: False
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
  # -----------------------
DATASETS:
  TRAIN: ("b2s_train",)
  TEST: ("b2s_val",)

  # Fraction of positive samples in each batch of proposals pos:neg - 1:5
  POSITIVE_FRACTION: 0.2
TRAINER:
  NAME: "B2STrainer"
DATALOADER:
  NUM_WORKERS: 4  # Adjust based on your CPU cores
SOLVER:
  # Because of the way RaCUN works right now, this NEEDS to be 1,
  # as different images have different number of proposals
  IMS_PER_BATCH: 1

  # Freeze ResNet backbone for a given number of iterations, then unfreeze for fine-tuning.
  BACKBONE_FREEZE_ITERS: 30000

  BASE_LR: 0.001
  STEPS: (26800, 42400, 84800)  # Adjust based on your dataset size and desired schedule
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 2500
  WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (300,)  # Match your image size
  MAX_SIZE_TRAIN: 300
  MIN_SIZE_TEST: 300
  MAX_SIZE_TEST: 300

  # Backward compatibility (doesn't do anything) ---
  MASK_FORMAT: "bitmask"
  # -----------------------
TEST:
  EVAL_PERIOD: 10000  # Evaluate every 10000 iterations
  EVALUATOR: "B2SEvaluator"
OUTPUT_DIR: "/home/s4861264/detectron2/projects/LoTSS-GRG-detect/output/racun_baseline/"


# BASELINE MODEL CONFIG FOR RACUN:
# - Added ROI Encoder before attention for better feature extraction from ROI features.
#   The ROI Encoder does not use BatchNorm2d
# - Added class token for ROI features to allow attention to learn a global
#   representation of the proposal region, which can be beneficial for classification tasks.
#   Uses the mean of the ROI features as the class token,
#   which provides a global summary of the proposal region.
# - Added ROI projector to align ROI feature dimension with
#   PhysicsFAN embedding dimension, which is necessary
#   for the attention fusion to work properly.
# - Fraction of positive samples in each batch pos:neg - 1:5
# - Freeze ResNet backbone till 30k iterations, then unfreeze for fine-tuning.
#   This allows the model to first learn good ROI and attention features before
#   fine-tuning the backbone on the specific dataset.
