# Dataset configuration for GRG detection
DATASET_NAME: "b2s"
TYPE: "b2s"
DATA_ROOT: "/home/s4861264/project_data/b2s_dataset"

TRAIN:
  EXISTS: True
  NAME: ""
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

VALIDATION:
  EXISTS: False
  NAME: ""
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

TEST:
  EXISTS: False
  NAME: ""
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"
