# Dataset configuration for GRG detection
DATASET_NAME: "b2s"
TYPE: "b2s_masked_rcnn"
DATA_ROOT: "/home/aurelsa/project_data/rgz_full_dataset_split"

TRAIN:
  EXISTS: True
  NAME: "train"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

VALIDATION:
  EXISTS: True
  NAME: "val"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"

TEST:
  EXISTS: True
  NAME: "test"
  ANNOTATIONS: "annotations.json"
  IMAGES: "images"
  PROPOSALS: "proposals"
