# e.g. projects/LoTSS-GRG-detect/config/custom_config.py
from detectron2.config import CfgNode as CN

def add_lotss_grg_config(cfg):
    cfg.MODEL.PHYSICS_FAN = CN()
    cfg.MODEL.PHYSICS_FAN.NUM_COMPONENTS = 10
    cfg.MODEL.PHYSICS_FAN.NUM_PHYSICS_FEATURES = 64
    cfg.MODEL.PHYSICS_FAN.EMBEDDING_DIM = 128
    cfg.MODEL.PHYSICS_FAN.EMBEDDING_DROPOUT = 0.0
    cfg.MODEL.PHYSICS_FAN.NUM_ATTENTION_HEADS = 8
    cfg.MODEL.PHYSICS_FAN.ATTENTION_DROPOUT = 0.0

    cfg.MODEL.FUSION_MODULE = CN()
    cfg.MODEL.FUSION_MODULE.TYPE = "AttentionFusionModule"
    cfg.MODEL.FUSION_MODULE.DROPOUT = 0.0
    cfg.MODEL.FUSION_MODULE.NUM_HEADS = 8

    cfg.MODEL.ROI_ALIGN = CN()
    cfg.MODEL.ROI_ALIGN.IN_FEATURES = ["p2", "p3", "p4", "p5"]
    cfg.MODEL.ROI_ALIGN.POOLER_RESOLUTION = 28
    cfg.MODEL.ROI_ALIGN.POOLER_SAMPLING_RATIO = 0
    cfg.MODEL.ROI_ALIGN.POOLER_TYPE = "ROIAlignV2"

    cfg.MODEL.VALIDITY_HEAD = CN()
    cfg.MODEL.VALIDITY_HEAD.LOSS_WEIGHT = 1.0
    cfg.MODEL.VALIDITY_HEAD.HIDDEN_DIM = 256

    cfg.MODEL.MEMBERSHIP_HEAD = CN()
    cfg.MODEL.MEMBERSHIP_HEAD.LOSS_WEIGHT = 1.0
    cfg.MODEL.MEMBERSHIP_HEAD.HIDDEN_DIM = 256

    cfg.TRAINER = CN()
    cfg.TRAINER.NAME = "GRGTrainer"